resolvers += Resolver.sonatypeRepo("releases")
addSbtPlugin("com.47deg"          % "sbt-org-policies"         % "0.11.3")
addSbtPlugin("com.47deg"          % "sbt-microsites"           % "0.9.3-SNAPSHOT")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.26")
